name: HTTP Config Enricher
language: python
variables:
  - name: DATA_TOPIC
    inputType: InputTopic
    description: Name of the data topic to listen to.
    required: true
  - name: CONFIG_TOPIC
    inputType: InputTopic
    description: Name of the config topic to listen to.
    required: true
  - name: OUTPUT_TOPIC
    inputType: OutputTopic
    multiline: false
    description: Name of the output topic to write to.
    required: true
  - name: LOOKUP_FIELDS_JSON
    inputType: FreeText
    multiline: true
    description: a JSON-serialized string that contains the desired field names with corresponding config field references. See 'get_fields' function in code for example.
    required: true
  - name: CONSUMER_GROUP_NAME
    inputType: FreeText
    multiline: false
    description: The name of the consumer group to use when consuming from Kafka.
    default: quix-configuration-enricher
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-transformation
