name: machine-configuration-ui
language: NodeJS
variables:
  - name: CONFIG_API_BASE_URL
    inputType: FreeText
    multiline: false
    required: true
dockerfile: dockerfile
runEntryPoint: build/index.js
defaultFile: src/routes/+page.svelte
