name: machine-config-form
language: Python
variables:
  - name: CONFIG_API_BASE_URL
    inputType: FreeText
    multiline: false
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: streamlit
